use super::*;

#[derive(Debug, Clone)]
pub(super) enum Message {
    SwitchView(View),
    ToggleLingqSettings,
    ClosePreview,
    BrowseSectionChanged(String),
    BrowseSearchChanged(String),
    BrowseToggleOnlyNew(bool),
    BrowseToggleArticle(String),
    BrowseRefresh,
    BrowseAllSections,
    BrowseLoadMore,
    BrowseSelectVisibleNew,
    BrowseClearSelection,
    BrowseFetchSelected,
    BrowseFindNew,
    BrowseLoaded {
        request_id: u64,
        result: Result<BrowseResponse, AppError>,
    },
    OpenPreview(String),
    OpenLibraryPreview(i64),
    PreviewLoaded(Box<Result<(Article, Option<StoredArticle>), AppError>>),
    OpenFullArticle(i64),
    LibrarySearchChanged(String),
    LibraryTopicChanged(String),
    LibraryToggleNotUploaded(bool),
    LibraryMinWordsChanged(String),
    LibraryMaxWordsChanged(String),
    LibrarySortChanged(LibrarySortMode),
    LibraryToggleDense(bool),
    LibraryToggleGroupByTopic(bool),
    LibraryToggleFilters,
    LibraryRefresh,
    LibrarySelectAllVisible,
    LibrarySelectAllNotUploaded,
    LibraryClearSelection,
    LibraryToggleArticle(i64),
    LibraryDeleteArticle(i64),
    LibraryNextPage,
    LibraryPrevPage,
    ArticleBack,
    ArticleCopyText,
    OpenArticle(i64),
    LingqAuthModeChanged(LingqAuthMode),
    LingqUsernameChanged(String),
    LingqPasswordChanged(String),
    LingqApiKeyChanged(String),
    LingqConnect,
    LingqDisconnect,
    LingqSignIn,
    LingqCollectionChanged(Option<i64>),
    LingqRefreshCollections,
    LingqLoggedIn(Result<String, AppError>),
    CollectionsLoaded(Result<Vec<Collection>, AppError>),
    LingqClearUploadSelection,
    LingqUploadSelected,
    BatchFetched {
        job_id: u64,
        saved_count: usize,
        saved_articles: Vec<ArticleListItem>,
        skipped_existing: usize,
        skipped_out_of_range: usize,
        failed: Vec<FailedFetchItem>,
        canceled: bool,
    },
    BatchUploaded {
        job_id: u64,
        uploaded: usize,
        successes: Vec<UploadSuccess>,
        failed: Vec<UploadFailure>,
        canceled: bool,
    },
    ContentRefreshCompleted {
        request_id: u64,
        reason: String,
        result: ContentRefreshResult,
    },
    ContentRefreshFailed {
        request_id: u64,
        reason: String,
        error: AppError,
    },
    CancelActiveJob,
    PauseQueue,
    ResumeQueue,
    RunQueuedUploadNow,
    ClearQueuedJobs,
    RetryFailedImports,
    RetryFailedUploads,
    SelectDiagnosticsJob(u64),
    OpenDataFolder,
    OpenLogFile,
    CopyRecentLog,
    CreateSupportBundle,
    ClearBrowseCache,
    CompactLocalData,
    RebuildSearchIndex,
    VerifyDatabase,
    ClearTaskFailures,
    OpenUrl(String),
    Tick,
}
